CREATE TABLE thongtin_giaohang (
  id INT AUTO_INCREMENT PRIMARY KEY,
  maDH INT NOT NULL,
  ho_ten VARCHAR(100) NOT NULL,
  sdt VARCHAR(20) NOT NULL,
  email VARCHAR(100),
  tinh VARCHAR(100) NOT NULL,
  quan VARCHAR(100) NOT NULL,
  phuong VARCHAR(100) NOT NULL,
  dia_chi TEXT NOT NULL,
  ghi_chu TEXT,
  FOREIGN KEY (maDH) REFERENCES donhang(maDH) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
